### ISSUE TITLE
本地的服务端错误

### ISSUE THREAD

**Issue by BARBERTONY1** [AlbertLeBron/tanshishe#2]
启动服务端，打开游戏，输入名字后进入到游戏画面中，画面空白，调出控制台，请求中有个post方法报错400，socket.io的cors已配，请问是什么问题？

**Comment by BARBERTONY1** [comment]
解决了，socket.io最近升级到3.0了，改了些东西，这个项目是2.0版本时的

**Comment by AlbertLeBron** [comment]
> 解决了，socket.io最近升级到3.0了，改了些东西，这个项目是2.0版本时的

**Comment by AlbertLeBron** [comment]
> 解决了，socket.io最近升级到3.0了，改了些东西，这个项目是2.0版本时的

我还没留意，感谢提醒
